updated init scripts, removed obsolete and unneeded files

diff --git a/debian/open-as-cgw.openas-quarantine-cron.init b/debian/open-as-cgw.openas-quarantine-cron.init
--- a/debian/open-as-cgw.openas-quarantine-cron.init
+++ b/debian/open-as-cgw.openas-quarantine-cron.init
@@ -26,56 +26,69 @@
 ### END INIT INFO
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PIDFILE=/var/run/openas-quarantine-cron.pid
 DAEMON=/usr/bin/quarantine-cron.pl
-NAME=quarantine-cron
-DAEMONNAME=quarantine-cron
-DESC=quarantine-cron
+NAME=openas-quarantine-cron
+DESC="Open AS Quarantine Cron"
 
-test -f ${DAEMON} || exit 0
-set -e
+do_start()
+{
+    echo -n "Starting $DESC: "
+    if start-stop-daemon --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas ${DAEMON} -- start >/dev/null ; then
+            echo "${NAME}."
+    else
+            if start-stop-daemon --test --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas ${DAEMON} >/dev/null 2>&1; then
+                    echo "(failed)."
+                    exit 1
+            else
+                    echo "(already running)."
+                    exit 0
+            fi
+    fi
+    echo "$NAME."
+}
 
-START="--start --quiet --pidfile /var/run/${NAME}.pid --name ${DAEMONNAME} --startas ${DAEMON}"
-STOP="--stop --quiet --pidfile /var/run/${NAME}.pid --name ${DAEMONNAME}"
-PARAMS=
+do_stop()
+{
+    echo -n "Stopping $DESC: "
+    if start-stop-daemon --stop --quiet --pidfile ${PIDFILE} --name ${NAME} --retry 10 >/dev/null ; then
+            echo "${NAME}."
+    else
+            if start-stop-daemon --test --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas ${DAEMON} >/dev/null 2>&1; then
+                    echo "(not running)."
+                    exit 0
+            else
+                    echo "(failed)."
+                    exit 1
+            fi
+    fi
+    echo "$NAME."
+}
 
 case "$1" in
   start)
-        echo -n "Starting $DESC: "
-        if start-stop-daemon ${START} -- ${PARAMS} start >/dev/null ; then
-                echo "${DAEMONNAME}."
-        else
-                if start-stop-daemon --test ${START} >/dev/null 2>&1; then
-                        echo "(failed)."
-                        exit 1
-                else
-                        echo "(already running)."
-                        exit 0
-                fi
-        fi
-        ;;
+    do_start
+    exit 0
+    ;;
+
   stop)
-        echo -n "Stopping $DESC: "
-        if start-stop-daemon ${STOP} --retry 10 >/dev/null ; then
-                echo "${DAEMONNAME}."
-        else
-                if start-stop-daemon --test ${START} >/dev/null 2>&1; then
-                        echo "(not running)."
-                        exit 0
-                else
-                        echo "(failed)."
-                        exit 1
-                fi
-        fi
-        ;;
-  restart|force-reload)
-        $0 stop
-        exec $0 start
-        ;;
+    do_stop
+    exit 0
+    ;;
+
+  restart)
+    do_stop
+    do_start
+    exit 0
+    ;;
+
+  status)
+    status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
+    exit 0
+    ;;
+
   *)
-        echo "Usage: $0 {start|stop|restart}" >&2
-        exit 1
-        ;;
+    echo "Usage: $0 {start|stop|restart|status}" >&2
+    exit 0
+    ;;
 esac
-
-exit 0
-
diff --git a/debian/open-as-cgw.openas-quarantine-ng.init b/debian/open-as-cgw.openas-quarantine-ng.init
--- a/debian/open-as-cgw.openas-quarantine-ng.init
+++ b/debian/open-as-cgw.openas-quarantine-ng.init
@@ -16,83 +16,79 @@
 # with the Open AS Communication Gateway. If not, see http://www.gnu.org/licenses/.
 #
 ### BEGIN INIT INFO
-# Provides:          quarantine-ng
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Provides:          openas-quarantine-ng
+# Required-Start:    $local_fs $network $remote_fs $syslog
+# Required-Stop:     $local_fs $network $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Init script for Open AS quarantine-ng.
-# Description:       Init script for Open AS quarantine-ng.
+# Short-Description: Init script for Open AS Quarantine NG.
+# Description:       Init script for Open AS Quarantine NG.
 ### END INIT INFO
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PIDFILE=/var/run/openas-quarantine-ng.pid
 DAEMON=/usr/bin/quarantine-ng.pl
-NAME=quarantine-ng
-DAEMONNAME=quarantine-ng
-DESC=quarantine-ng
+NAME=openas-quarantine-ng
+DESC="Open AS Quarantine NG"
 
-test -f ${DAEMON} || exit 0
+do_start()
+{
+    echo -n "Starting $DESC: "
+    if start-stop-daemon --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas ${DAEMON} -- start >/dev/null ; then
+            echo "${NAME}."
+    else
+            if start-stop-daemon --test --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas ${DAEMON} >/dev/null 2>&1; then
+                    echo "(failed)."
+                    exit 1
+            else
+                    echo "(already running)."
+                    exit 0
+            fi
+    fi
+    echo "$NAME."
+}
 
-set -e
-
-START="--start --quiet --pidfile /var/run/${NAME}.pid --name ${DAEMONNAME} --startas ${DAEMON}"
-STOP="--stop --quiet --pidfile /var/run/${NAME}.pid --name ${DAEMONNAME}"
-PARAMS=
+do_stop()
+{
+    echo -n "Stopping $DESC: "
+    if start-stop-daemon --stop --quiet --pidfile ${PIDFILE} --name ${NAME} --retry 10 >/dev/null ; then
+            echo "${NAME}."
+    else
+            if start-stop-daemon --test --start --quiet --pidfile ${PIDFILE} --name ${NAME} --startas ${DAEMON} >/dev/null 2>&1; then
+                    echo "(not running)."
+                    exit 0
+            else
+                    echo "(failed)."
+                    exit 1
+            fi
+    fi
+    echo "$NAME."
+}
 
 case "$1" in
   start)
-        echo -n "Starting $DESC: "
-        if start-stop-daemon ${START} -- ${PARAMS} start >/dev/null ; then
-                echo "${DAEMONNAME}."
-        else
-                if start-stop-daemon --test ${START} >/dev/null 2>&1; then
-                        echo "(failed)."
-                        exit 1
-                else
-                        echo "(already running)."
-                        exit 0
-                fi
-        fi
-        ;;
+    do_start
+    exit 0
+    ;;
+
   stop)
-  		# HACK HACK HACK
-  		exit 0;
-        echo -n "Stopping $DESC: "
-        if start-stop-daemon ${STOP} --retry 10 >/dev/null ; then
-                echo "${DAEMONNAME}."
-        else
-                if start-stop-daemon --test ${START} >/dev/null 2>&1; then
-			PID_PIDFILE=`cat /var/run/${NAME}.pid`
-			PID_PSAUX=`ps aux | grep ${DAEMONNAME} | grep -v grep | awk '{print $2}'`
+    do_stop
+    exit 0
+    ;;
 
-			if [ $PID_PIDFILE -ne $PID_PSAUX ]; then
-				echo "(process PID and pidfile PID are inconsistent)";
-				rm /var/run/${NAME}.pid
-				killall ${NAME}
-			fi		
-	
-                        echo "(not running)."
-                        exit 0
-                else
-                        echo "(failed)."
-                        exit 1
-                fi
-        fi
-        ;;
-  reload)
-        echo -n "Reloading $DESC: "
-        kill -s HUP `cat $PIDFILE`
-        echo "$NAME."
-        ;;
-  restart|force-reload)
-        $0 stop
-        exec $0 start
-        ;;
+  restart)
+    do_stop
+    do_start
+    exit 0
+    ;;
+
+  status)
+    status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
+    exit 0
+    ;;
+
   *)
-        echo "Usage: $0 {start|stop|restart}" >&2
-        exit 1
-        ;;
+    echo "Usage: $0 {start|stop|restart|status}" >&2
+    exit 0
+    ;;
 esac
-
-exit 0
-
